# Generated by Django 5.2 on 2025-04-22 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectimprovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectImprovement',
        ),
    ]
