# Generated by Django 5.2 on 2025-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectcomment_read_by_delete_projectimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this project is approved by admin'),
        ),
    ]
