# Generated by Django 5.2 on 2025-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_early_date',
            field=models.DateField(blank=True, help_text='Date when project was marked as completed early', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes about project completion', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.FileField(blank=True, help_text='Project documentation or files', null=True, upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('completed_early', 'Completed Early')], default='active', max_length=20),
        ),
    ]
