# Generated by Django 5.2 on 2025-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_company_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this user is approved to access the system'),
        ),
        migrations.AlterField(
            model_name='company',
            name='access_code',
            field=models.CharField(default='022a9a2e', max_length=20, unique=True),
        ),
    ]
