# Generated by Django 5.2 on 2025-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_userprofile_is_approved_alter_company_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_code',
            field=models.CharField(default='43587439', max_length=20, unique=True),
        ),
    ]
